sudo: false
language: groovy
jdk:
  - oraclejdk8

before_install:
 - "export TRAVIS_COMMIT_MSG=$(git log --format=%B -n 1 $TRAVIS_COMMIT)"
 - git config user.email "szpak-ci@users.noreply.github.com"
 - git config user.name "Szpak CI Bot"
 - git --version

install: ./gradlew assemble --stacktrace --info
script:
 - ./gradlew prepareForCiBuild -s -i -PdeliveryBoy.dryRun=false -Prelease.disableChecks && ./gradlew ciBuild -s -i -PdeliveryBoy.dryRun=false -Prelease.disableChecks -Prelease.customUsername=SEC_TOKEN

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -fr $HOME/.gradle/caches/*/scripts-remapped/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
  - secure: aKGSUT3EQ8pIng5jbr+VUgc9gPgW7UKRMKW9QBJtjuSbQQsSQh7hfsJj09ySy1wP00f+kQOtm9VVNMJ6vUVR38v2RRmCmiqwMsp6G9ix5kcg9H/bapDFP2RodZzZSYzHlie2sor5u1nm/j84pN2Xfud/DOP82d16IfZU5gkwh+LxQkxyGaCAVa6Q6f4c0Fr6h1eyxtrLzLCGdV1Vs+ANik6oo2uzGDjSTlOO2fd0UR9RLh6uOZQmzth7x8PzR7Kohh7BUp4ADa0YbBIA79i5ghEcFZwWyuThOdICzymx6gXID79VI5ChAhwe0SbtpFSW+kqylWup89cGAgwTC6jRlQuTpQ6HT5g9CgO2nslfS/4kgJV0NHGo5oZq7+xNbsD0rXgBaLT0qVp+/kwD0mkPgW2GAd+F0hITEEAQUeehleuYZFYGIoPri72o8folXMSFuKNdBL9i+LxsSL/QjCocjAxmpXKaRsTnRLUKs0FA6LcpEznPaxHGbBXxOb1XTb6wk9LiclscAQUXvI9/0RtHTXxzQrGZXzWTjejRiv3S4VwdHEzij3iT27iuZ0MY2eXXL5X6RyXIfbAX5I70PBHZ1b2puB6KUHVurN4T1qvQAq3BEvHCZrPQw3dYeXmAkgLKUL6IG24/+JoCgF4P33rWuibObfh9j+v0LlzCL/ZPBr4=
  - secure: oXqRjmvYSwbday2IBvGGOwLFli1sU+01Rk1tA1aOPx8NSQ8XhaP4L2aQdHPEvmSSO1ZmT+VFCx5Gfj5tFk+eqjhy9u3e81dSA35P/+BVoC2nVrV9h++RB5YPLTg9U3aTUV7Mme4X96ktY/b1cGP8RyNnJTmh1WEcW3XhQ9x7A8mDcU3UKO5HEQMr+mAdGl6XV09L2iJbK8IjAE2or+vo2Gp13sOS39yBbn45+xeKi91lYvvlYaDgxRXd7VOfIOGQqSCnd1p1bFHGwXfocxzyRiCgoHSshHOARAvMnYugk8MZiBoNc8vDce28ijELmjXaL1V9YJ7tv4yfVKC5Ryb8qZiwVsUNWv7K+YifK7aej9IcDQJthWSKkKeUe7b972PvVjcyMO5f7Z+iQPxxuVY5llqbgRVSbzHP+gwzVn+cLA2fWM7vf2N0JKODdGDrm/kEDlMET/5D7b8FlPs4yCK75TS6s5YYfnrpf2nbdjsvS4lRn3FVSad3gkkg+ubZQi6EiZIMO1OpRMOjjjPSovgypMrDZCKpiGc6UVnAjGr9rqJof0X0PZ4J7FcKbZaYn5PxtBWnXe2JZm+Dnrn6sNXyCxQpBMkro55speRWE7Uz1WTlmTGBwCqLfrq8dCLlSvKiMU7C+7Kv4OodnkA+TEhxl2FCtqeUybC2AhUO25ln6ls=
  - secure: jqXIMQXXVKPLhDCID2cyiH+J3ztRveK+7Jcc+bF/SVjDl0aqflANcg25ewp2vpy4dITdZrNHJzXMyLgnWeEdBij/9UfQ1wHmolwqFi8O8+twuXsfdNTILWIoDfY7nmHta7k1OIl2ZhGh9gfyGnSCYWfMWQpCwqAh59Q7qxRwuggUoSmKeBqhJRetSuzHnkbGf1wbCjNQJ9vbGfjsT4l6mJ1SZ9TOY7U0pOcxKgVn/uRv9du0wAF202p8pqxfmFQnF612wGVotnnbPXOW1cBQJ/eOBB7puq9w3YlqV5nJP5ytmldtJ8k3ZSIQuH7ZPV3XRiNLcwsvOD+KTmSytokrAwNIU+qBQTK2g0z+Txqo2C51+pSOg9UEjgfDnfIcz0cctVa+25yw5fWURD+JPI9f/f8bw7XDxwkxb9bWqAiGOeXhH2C076jg9EGkHryHm7AzYs0kO/Gv1uXZBZ+6NrJUgY6wfr+wBMpUoxuLgadx+ugKHZTavuxPu0CshZ+l2CKgp1he4KLUrEgzGt8etpRVOGRSVmGuM9l1lHyKATZhrVAuFOh9eHl1WtPloAB+iZF9xPqtjNQzZ3np4NQa+QiEB3m6hd8m6eg1LFd88VzSgk4mYcvhVBBp8toCxqtD2m7GeOCS4UhhGzrM6UKvxBxIF15WUyS57KC1sARqLIZHsG8=
