sudo: false
language: groovy
jdk:
  - oraclejdk8

before_install: "export TRAVIS_COMMIT_MSG=$(git log --format=%B -n 1 $TRAVIS_COMMIT)"
install: ./gradlew assemble --stacktrace --info
script: ./gradlew prepareForCiBuild --stacktrace --info -PdeliveryBoy.dryRun=false -Prelease.disableUncommittedCheck && ./gradlew ciBuild --stacktrace --info -PdeliveryBoy.dryRun=false -Prelease.disableUncommittedCheck
